global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'importer'
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'processor'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor-dev:8080']


