global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'importer'
    static_configs:
      - targets: ['importer:3000']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'processor'
    static_configs:
      - targets: ['processor:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']


