common:
  project_name: noname
  database_url: postgresql://postgres:postgres@0.0.0.0:5432/frida
  redis_host: localhost
  redis_port: 6379
  redis_username: default
  redis_password: default
  redis_db: 0
  redis_ns: frida

importer:
  server_address: 0.0.0.0:3000
  log_level: info
  metrics_path: /metrics

backend:
  server_address: 0.0.0.0:8000
  log_level: info
  metrics_path: /metrics

processor:
  threads: 2
  log_level: info
  sleep_ms: 100
  metrics_address: 0.0.0.0:9100
  matcher_configs: {}